apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-app
  namespace: quest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quest-app
  template:
    metadata:
      labels:
        app: quest-app
    spec:
      serviceAccountName: quest-app-sa
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
      - name: quest-app
        image: 904233133644.dkr.ecr.ap-south-1.amazonaws.com/quest-dev-app:latest
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: SECRET_WORD
          valueFrom:
            secretKeyRef:
              name: quest-secrets
              key: secret-word
              optional: false